version: "3.2"

services:
  webserver:
    container_name: ws_gtm
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=localhost
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./:/var/www
    links:
      - db

    depends_on:
      - db

  db:
    container_name: db_gtm
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 9514:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_gtm
      MYSQL_USER: don
      MYSQL_PASSWORD: 1234qwer
