<?php

namespace common\models;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "comment".
 *
 * @property int $id
 * @property int $task_id
 * @property string $text
 *
 * @property Task $task
 */
class Comment extends ActiveRecord
{
	/**
	 * {@inheritdoc}
	 */
	public static function tableName()
	{
		return 'comment';
	}

	/**
	 * {@inheritdoc}
	 */
	public function rules()
	{
		return [
			[['task_id', 'text'], 'required'],
			[['task_id'], 'integer'],
			[['text'], 'string'],
			[['task_id'], 'exist', 'skipOnError' => true, 'targetClass' => Task::class, 'targetAttribute' => ['task_id' => 'id']],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'task_id' => 'Task',
			'text' => 'Text',
		];
	}

	// public function beforeValidate()
	// {
	// 	$this->author_id = Yii::$app->user->id;
	// 	return parent::beforeValidate(); // TODO: Change the autogenerated stub
	// }

	public function getTask(): ActiveQuery
	{
		return $this->hasOne(Task::class, ['id' => 'task_id']);
	}
}
